AhnSeene/find-my-meme-frontend

package-lock.json, package.json, src/pages/Login.css, src/pages/Login.js
close #4
로그인 틀 생성
아이디 입력칸, 비밀번호 입력칸, 로그인 버튼 생성
=> Feat/ 로그인 틀 만들기

src/App.js, src/components/Header.css, src/components/Header.js, src/contexts/AuthContext.js, src/pages/Home.js, src/pages/Login.css, src/pages/Login.js
close #6 
로그인 안 했을 때는 회원가입,로그인 버튼이 보이게하고
로그인 했을 때는 짤등록, 마이페이지 버튼이 보이게 수정
isLoggedin을 전역으로 관리 (useContext 사용)
=> Feat/header 조건부 렌더링으로 헤더 만듬

package-lock.json, package.json, src/App.js, src/components/Header.js, src/pages/UploadMeme.css, src/pages/UploadMeme.js
close #8 
Meme에 태그를 등록해서 올릴 수 있다
=> [Feat] Upload meme 기능 추가

src/App.js, src/pages/SignUp.js, src/pages/signup.css
close #12 
실시간 유효성 검사
아이디, 비밀번호, 비밀번호 확인 칸
오류 메세지 출력
=> feat: 회원가입 기능 구현

src/App.js, src/components/Header.js, src/pages/FindMeme.js, src/pages/findmeme.css
close #15 
글제목, 글내용( 글자 제한하고 '...'로 보이게 설정)
이미지 있을경우 이미지 보이게
찾아줘, 찾았다 버튼에 따라 보이는 게시글 다르게 설정
=> Feat/findmymeme 페이지 기능 구현

package-lock.json, package.json, src/App.js, src/pages/FindMeme.js, src/pages/FindMemePost.js, src/pages/findmemepost.css
close #17 
찾아줘 게시글 등록, 찾아줘, 찾았다 글 서버에서 불러오는 기능 추가
=> Feat/findmemepost 기능 구현

src/App.js, src/components/Header.js, src/components/Profile.js, src/pages/MyPage.js, src/pages/mypage.css
close #19 
마이페이지에 nav바 만들고 프로필 컴포넌트 구현
=> [Feat] 마이페이지 기능 구현

src/components/CommentForm.js, src/components/CommentList.js, src/components/commentform.css, src/components/commentlist.css
close #23 
댓글 폼 컴포넌트, 댓글목록컴포넌트 구현
=> feat: 댓글 폼, 댓글, 대댓글 기능 구현

src/App.css, src/components/Header.css, src/components/Navbar.css
스크롤 시 Navbar 화면에 고정되게 수정 
Header 바로 밑에 Navbar오게 위치 조정
=> design: Navbar 화면에 고정되게 수정

src/pages/FindMeme.js, src/pages/findmeme.css
close #26 
날짜 포맷팅해서 작성시간 보이게 수정
페이징 기능 구현(서버에 요청)
=>  feat: findmemepost에 작성시간 보이게 수정, 페이징 기능 구현

src/pages/FindMemePost.js
close #28 
글 내용 중 사진 없이 글 내용만 서버에 전달
=> feat: findmemepost 등록시 사진없이 내용만 서버에 전달하는 기능 구현

src/pages/FindMemeDetail.js, src/pages/findmemedetail.css
close #30 
commentForm, commentList import
댓글 입력 칸 추가 ( 클릭시 실제 commentForm 등장)
댓글들 관리
=>  feat: findmemedetail페이지에 댓글 입력칸 추가, 댓글 관리 기능 구현

src/App.js, src/pages/FindMemeEdit.js
close #32 
findmemepost 수정버튼 눌렀을 때 기존 내용 불러온 editor창 구현
=> Feat/ findmemeEdit 기능 구현

src/components/TagSelector.js
close #34 
부모태그/하위태그  태그 선택, 태그취소 구현
=> feat: 태그 컴포넌트 생성

src/pages/Admin.js, src/pages/admin.css
design: admin페이지 css 구현
close #36 
admin페이지. 태그 생성 기능
=> feat: admin 페이지 구현, 태그 생성기능 구현

src/pages/Login.js
로그인 시 storage에 토큰, username 저장
=> feat: 로그인 시 토큰, 유저네임 저장

src/contexts/AuthContext.js
close #43 
로그인 시 세션에 token, username 저장
로그아웃 기능 구현
=> feat: 로그인, 로그아웃 기능 구현

src/components/MyInfo.js, src/components/Profile.js, src/components/profile.css, src/pages/MyPage.js
close #45 
로그인 했을 시에 프로필/ 내가 작성한 게시글/내 정보 불러오게 하고 프로필 수정 가능하게 함
로그인 안 했을 시에 프로필/작성 게시글 불러오기
=> [Feat] 마이페이지 구현

src/components/Header.css, src/components/Header.js, src/components/Navbar.css, src/components/Navbar.js
close #47 
마이페이지 드롭바에 내정보, 프로필,로그아웃 항목 구현
=> Navbar에 드롭바 기능 추가, header항목 이름 변경

src/pages/FindMemeEdit.js, src/pages/FindMemePost.js, src/pages/findmemepost.css
close #49 
글 작성 시에 태그 선택하게 수정, 글 수정 시에도 선택되었던 태그 불러오고 수정가능하게 수정.
=> [feat] Findmemepost 작성 시, 수정 시 태그 추가

src/components/MemeSlider.js, src/components/MemeSwiper.js
close #51 
추천이미지 보여주는 슬라이드
사진여러개 모아 보여주는 두 줄 슬라이드,(한번에 10개씩 넘어가게)
=> [Feat/slider] 슬라이더 기능 구현

src/pages/UploadMeme.js
close #53 
태그 id랑 태그 name 연결. 서버에 사진 전동
=> feat: uploadmeme에 태그 기능 추가, 서버에 사진 전송

src/pages/Home.js, src/pages/home.css
close #55 
스크롤 시 이미지 불러오게, 좋아요버튼 기능 구현
좋아요버튼이 사진 우측하단에 위치하게
=> [feat/home] 스크롤 시 이미지 불러오게, 좋아요 기능 구현

src/contexts/api.js
close #58 
axios에 서버요청시 헤더에 토큰추가하여 불러오게 하는 api 컴포넌트 구현
=> feat: 헤더에 토큰 추가하기. axios대신 api 사용하게 수정

src/components/PostForm.js, src/pages/FindMeme.js, src/pages/FindMemeDetail.js, src/pages/findmeme.css, src/styles/common.css
close #60 
글 작성할때 reactquill 에디터 추가
=> [feat/Findmeme] 글 작성 폼 구현

src/pages/MemeDetail.js, src/pages/memedetail.css
close #62 
meme 사진, 상세 정보, 사진 등록한 유저 닉네임, 유저닉네임 프로필사진, 다운로드 버튼, 공유버튼, 추천 이미지 보여주게 구현
=> [feat/memedetail] meme 상세페이지 구현

src/pages/TopMeme.js
close #64 
좋아요 높은 이미지, 조회수 높은 이미지, 일주일간 좋아요 높은 순 이미지 보여주는 페이지 구현( 슬라이드 형식)
=>  [feat] topmeme 페이지 구현

.gitignore, package-lock.json, package.json, src/App.js, src/index.js, src/pages/findmemedetail.css
=> Feat/chore swiper 설치, route추가

src/components/CommentList.js, src/pages/FindMemeDetail.js
close #67 
답글 삭제시 서버에 삭제요청 후 받은 응답내용으로 업데이트
답글 삭제시 삭제 시간 표시
답글 창 열리는 위치 변경
=> [Feat/comment] 답글 삭제 시 내용 업데이트, 답글창 위치 변경

src/contexts/api.js, src/pages/Admin.js, src/pages/FindMeme.js, src/pages/Home.js, src/pages/Login.js, src/pages/SignUp.js, src/pages/UploadMeme.js
close #69 
백엔드 서버 호출 환경변수로 설정
api 컴포넌트 import
=> [Feat/api] 백엔드 서버 호출 환경변수로 설정

src/components/Header.css, src/components/Header.js, src/components/Navbar.css
close #71 
logo 사진 삽입, 로고 위치 조정
=>  design: logo 사진 삽입, 위치 조정

.dockerignore, .github/workflows/build-and-push.yml, .github/workflows/deploy.yml, Dockerfile, src/nginx/nginx.conf
=> [Deploy] docker 배포

Dockerfile
=> fix: Dockerfile nginx.config 위치 수정

Dockerfile
=> fix: Dockerfile nginx.config 위치 에러 해결

nginx/nginx.conf
=> rename: nginx.config 폴더 위치변경

.github/workflows/build-and-push.yml
=> fix: docker push tag name chage

.github/workflows/deploy.yml
=> fix: deploy compose env name change

nginx/nginx.conf
=>  feat: nginx.conf 수정

.github/workflows/build-and-push.yml
=> feat: buildandpush 수정

.github/workflows/deploy.yml
=> feat: deploy.yml 수정

.github/workflows/build-and-push.yml
=>  feat: build and push 수정

src/contexts/api.js
=>  feat: api 컴포넌트 수정

src/pages/SignUp.js
=> feat: 중복검사 서버연결

nginx/nginx.conf
=>  feat: nginx.config 수정

nginx/nginx.conf
=> feat: nginx.conf 수정

nginx/nginx.conf
=> feat: nginx.config에 .well-knon/acme-challeng경로 추가

nginx/nginx.conf
=> feat: nginx.config https 관련 설정 추가

nginx/nginx.conf
=> feat: nginx.config https관련 주석 처리

nginx/nginx.conf
=> feat: nginx.conf certbot 관련 설정 추가

nginx/nginx.conf
=> feat: nginx.conf cert 권한 설정

nginx/nginx.conf
=> fix: nignx.conf 괄호 오타 삭제

nginx/nginx.conf
=> feat: nginx.conf https 리다이렉션 주석 처리

nginx/nginx.conf
=> fix: nginx.conf /.well-known/acme-challenge/ 수정

nginx/nginx.conf
=> feat: nginx.conf ssl 적용

.github/workflows/deploy.yml, src/components/PrivateRoute.js, src/contexts/AuthContext.js, src/pages/Login.css, src/pages/Login.js
close #111 
- [ x] 기능개발(Feature)
아이디 저장 버튼 추가.
아이디가 로컬스토리지에 저장됨
=> Login 아이디 저장버튼 

src/App.js, src/components/MemeSwiper.css, src/components/MemeSwiper.js, src/components/Navbar.css, src/components/Navbar.js, src/components/Profile.js, src/pages/Home.js, src/pages/MemeDetail.js, src/pages/home.css, src/pages/mypage.css
- [x ] 기능개발(Feature)
css 수정, meme에 다운로드도 보이게 수정
=> Feat css 수정

.github/workflows/deploy.yml, nginx/nginx.conf
=> [chore] nginx.conf 모든 요청을 받도록 수정,  deploy.yml 환경변수 추가

.github/workflows/deploy.yml, nginx/nginx.conf
=> [Feat] api 호출 변경

src/pages/FindMeme.js
=> fix: 찾았다 게시글 목록 api 호출 url 수정

src/pages/UploadMeme.js
=> feat: 파일 업로드 방식을 Multipart 에서 PresignedURL을 사용하는 것으로 바꿈

src/pages/Login.js, src/pages/SignUp.js
=> Fix: 이메일 중복검사 기능 구현

src/pages/FindMeme.js
=> fix : findmeme에서 페이지 네이션 오류 수정

src/hooks/useToggleLike.js, src/pages/FindMeme.js
=> fix: 로그아웃 상태에서 밈 좋아요 버튼 작동 안하게 수정

.github/workflows/build-and-deploy.yml
=> fix: build-and-deploy.yml에서 npm ci시 CI=false 추가

.github/workflows/build-and-deploy.yml
=> fix: deploy.yml에서 cross-env를 통해 환경변수 전달

src/components/TagSelector.js
=> fix: Tagselector의 ParentTag찾는 필요없는 코드 수정

src/components/MemeGrid.js, src/hooks/useInfiniteMemesQuery.js, src/hooks/useToggleLike.js, src/pages/Home.js
=> fix: 불필요한 props 전달 수정

src/App.css, src/App.js, src/components/BottomNavbar.js, src/components/bottomNavbar.css
=> feat: 모바일 크기에 bottomNavbar 생성되게 수정

src/components/TagSelector.js, src/pages/FindMeme.js, src/pages/FindMemeEdit.js, src/pages/FindMemePost.js, src/pages/Home.js, src/pages/findmeme.css, src/pages/home.css
=> fix: 불필요한 코드 수정

src/components/MemeGrid.js, src/components/MemeSlider.js, src/components/memeSlider.css, src/pages/TopMeme.css, src/pages/TopMeme.js
=> fix: Topmeme ui/ux 수정

src/components/BottomNavbar.js, src/components/MemeSlider.js, src/components/bottomNavbar.css, src/components/memeSlider.css
=> fix: props변경

src/components/MemeGrid.js, src/hooks/useInfiniteMemesQuery.js, src/hooks/useToggleLike.js, src/pages/Home.js
태그 필터 변경 시 meme 목록 갱신되지 않던 버그 수정
react querykey 추가
=> fix: 태그 필터 변경 시 meme 목록 갱신되지 않던 버그 수정

package-lock.json, package.json, src/App.js, src/components/Header.js, src/components/Navbar.js, src/contexts/api.js, src/pages/FindMeme.js, src/pages/MemeDetail.js
=> feat: toast 설치 후 toast 알림 메시지 설정

src/components/MemeSlider.js, src/pages/Login.js
=> Fix:props undefined 오류 해결

src/pages/MemeDetail.js
=> fix: 밈 다운로드 방법 수정

src/components/comment/CommentForm.js, src/components/meme/MemeGrid.js, src/components/meme/MemeSlider.js, src/components/meme/MemeSwiper.js, src/components/myPage/Profile.js, src/pages/FindMeme/FindMemeEditPage.js, src/pages/FindMeme/FindMemePostPage.js, src/pages/MemeDetail/MemeDetailPage.js, src/pages/UploadMeme/UploadMemePage.js
모든 컴포넌트에서 REACT_APP_FILE_BASEURL 환경변수 사용을 제거하고
서버 제공 절대 URL을 직접 사용하도록 변경
close #165 
=> refactor: fileBaseUrl 사용 제거, 서버 절대 URL 사용
